# Generated by Django 4.2.1 on 2023-05-24 00:24

from django.db import migrations, models
import django.db.models.deletion
import election.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('n_box', models.IntegerField()),
                ('n_voter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VoteReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('n_valid', models.IntegerField()),
                ('n_invalid', models.IntegerField()),
                ('n_kk', models.IntegerField()),
                ('n_rte', models.IntegerField()),
                ('file', models.FileField(upload_to='reports', validators=[election.models.validate_file_extension, election.models.validate_file_size])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='election.box')),
            ],
        ),
        migrations.CreateModel(
            name='VoteReportVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField()),
                ('result', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='election.votereport')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('n_box', models.IntegerField()),
                ('n_voter', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='election.city')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='election.district'),
        ),
        migrations.AddConstraint(
            model_name='votereportverification',
            constraint=models.UniqueConstraint(fields=('report', 'source_ip'), name='report_source_ip_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='votereport',
            constraint=models.UniqueConstraint(fields=('version', 'box'), name='version_box_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('number', 'district'), name='box_number_district_unique_constraint'),
        ),
    ]
