# Generated by Django 4.2.1 on 2023-05-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('slug', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('version', models.IntegerField(default=1)),
                ('n_vote_kk', models.IntegerField()),
                ('n_vote_rte', models.IntegerField()),
                ('file', models.FileField(upload_to='reports')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='election.box')),
            ],
        ),
        migrations.CreateModel(
            name='VoteReportVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.GenericIPAddressField()),
                ('result', models.BooleanField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='election.votereport')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='election.city')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='election.district'),
        ),
        migrations.AddConstraint(
            model_name='votereportverification',
            constraint=models.UniqueConstraint(fields=('report', 'source_ip'), name='report_source_ip_unique_constraint'),
        ),
    ]
