# Generated by Django 4.2.1 on 2023-05-22 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votereport',
            old_name='n_vote_kk',
            new_name='n_kk',
        ),
        migrations.RenameField(
            model_name='votereport',
            old_name='n_vote_rte',
            new_name='n_rte',
        ),
        migrations.AddField(
            model_name='votereport',
            name='n_invalid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votereport',
            name='n_valid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votereportverification',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votereportverification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
