# Generated by Django 4.2.1 on 2023-05-24 04:47

from django.db import migrations, models
import election.models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votereport',
            name='file',
            field=models.FileField(upload_to=election.models.VoteReport.get_file_path, validators=[election.models.validate_file_extension, election.models.validate_file_size]),
        ),
    ]
