# Generated by Django 4.2.1 on 2023-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_n_vote_kk_votereport_n_kk_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('number', 'district'), name='box_number_district_unique_constraint'),
        ),
    ]
