# Generated by Django 4.2.1 on 2023-05-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_box_box_number_district_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votereport',
            name='number',
        ),
    ]
