# Generated by Django 4.2.1 on 2023-05-22 20:52

from django.db import migrations, models
import election.models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_remove_votereport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votereport',
            name='file',
            field=models.FileField(upload_to='reports', validators=[election.models.validate_file_extension, election.models.validate_file_size]),
        ),
    ]
