# Generated by Django 4.2.1 on 2023-05-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_alter_votereport_file'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votereport',
            constraint=models.UniqueConstraint(fields=('version', 'box'), name='version_box_unique_constraint'),
        ),
    ]
