# Generated by Django 4.2.1 on 2023-05-23 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_votereport_version_box_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votereport',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='votereportverification',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
