# Generated by Django 4.2.1 on 2023-05-23 00:17

from django.db import migrations, models
import election.models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_alter_votereport_id_alter_votereportverification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='votereport',
            name='source_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
