# Generated by Django 4.2.1 on 2023-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_votereport_source_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='n_boxes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='n_voters',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
