# Generated by Django 4.2.1 on 2023-05-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_city_n_boxes_city_n_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
