# Generated by Django 4.2.1 on 2023-05-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_remove_city_n_boxes_remove_city_n_voters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='n_boxes',
            new_name='n_box',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='n_voters',
            new_name='n_voter',
        ),
    ]
