# Generated by Django 4.2.1 on 2023-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_rename_n_boxes_district_n_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='n_box',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='n_voter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
