# Generated by Django 4.2.1 on 2023-05-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_city_n_box_city_n_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='election.district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='election.city'),
        ),
        migrations.AlterField(
            model_name='votereport',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='election.box'),
        ),
        migrations.AlterField(
            model_name='votereportverification',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='election.votereport'),
        ),
    ]
